name: Mirror to second repo

on:
  push:
    branches:
      - main

permissions:
  contents: write        # allows checkout & commit code
  workflows: write       # **crucial** for updating workflow files

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout using PAT
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.MIRROR_TOKEN }}   # ensures PAT (not GITHUB_TOKEN) is used

      - name: Push to second repo
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git remote add mirror \
            https://x-access-token:${{ secrets.MIRROR_TOKEN }}@github.com/gmc-mbnr/T2P.git
          git push mirror main --force
