name: Mirror to second repo

on:
  push:
    branches:
      - main

permissions:
  contents: write
  workflows: write

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout full history with PAT
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.MIRROR_TOKEN }}

      - name: Push entire branch forcefully
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git remote add mirror https://x-access-token:${{ secrets.MIRROR_TOKEN }}@github.com/gmc-mbnr/T2P.git
          git push mirror refs/heads/main:refs/heads/main --force
