name: Mirror to second repo

on:
  push:
    branches:
      - main

permissions:
  contents: write    # allows checkout of private repo with GITHUB_TOKEN

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source with default token
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # persist-credentials defaults to true, so GITHUB_TOKEN is set for origin

      - name: Remove built‑in credentials so PAT is used for push
        run: |
          git remote remove origin

      - name: Make orphan branch without workflows
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git checkout --orphan mirror-branch
          git rm -rf --cached .
          git reset --hard
          git checkout main -- .
          rm -rf .github
          git clean -fdx
          git add .
          git commit -m "Mirror without workflows" --allow-empty

      - name: Push clean branch with mirror PAT
        run: |
          git remote add mirror \
            https://x-access-token:${{ secrets.MIRROR_TOKEN }}@github.com/gmc-mbnr/T2P.git
          git push mirror HEAD:main --force
