name: Mirror to second repo

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source without GITHUB_TOKEN
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false    # ← disable injected GITHUB_TOKEN

      - name: Configure Git user
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Prepare clean mirror branch
        run: |
          git checkout --orphan mirror-branch
          git rm -rf --cached .
          git reset --hard origin/main
          rm -rf .github
          git clean -fdx
          git add .
          git commit -m "Mirror without workflows" --allow-empty

      - name: Push via PAT
        run: |
          git remote add mirror "https://x-access-token:${{ secrets.MIRROR_TOKEN }}@github.com/gmc-mbnr/T2P.git"
          git push mirror HEAD:main --force
